# Generated by Django 3.2.6 on 2021-08-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='images/items/%Y/%m/%d', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
