# Generated by Django 3.2.6 on 2021-09-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(help_text='Не более 500 знаков', max_length=500, verbose_name='описание'),
        ),
    ]
